# Generated by Django 5.2.1 on 2025-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
